[package]
name = "precache"
version = "0.1.0"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]

[dependencies]
log = "0.3"
pretty_env_logger = "0.1.1"
netlink-rs = "0.0.3"
nix = "0.9"
byteorder = "1.1.0"
bytevec = "0.2.0"
libc = "0.2.30"
procmon_sys = { version = "0.0.1", path = 'src/procmon_sys' }
