[package]
name = "precached"
version = "0.1.0"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
description = "A Linux process monitor and pre-caching daemon"
repository = "https://github.com/X3n0m0rph59/precached"
homepage = "https://x3n0m0rph59.github.io/precached/"
license = "GPLv3+"
readme = "README.md"

[dependencies]
procmon-sys = { version = "0.0.2", path = 'src/procmon-sys' }
sys-info = { git = "https://github.com/X3n0m0rph59/sys-info-rs" }
threadpool = { git = "https://github.com/X3n0m0rph59/rust-threadpool" }
chrono = { version = "0.4.0", features = ["serde"] }
libc = "0.2.32"
nix = "0.9"
log = "0.3"
env_logger = "0.4.3"
pretty_env_logger = "0.1.1"
fern = "0.4"
ansi_term = "0.10.2"
syslog = "~3.3.0"
lazy_static = "0.2.8"
regex = "0.2"
fnv = "1.0.5"
globset = "0.2"
byteorder = "1.1.0"
bytevec = "0.2.0"
toml = "0.4"
clap = "2.26.2"
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"
zstd = "0.4.16"
dbus = "0.5.4"
notify-rust = "3"
term = "0.4.6"
prettytable-rs = "^0.6"
daemonize = "0.2.3"
clippy = { version = "*", optional = true }

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "precached"
path = "src/main.rs"

[[bin]]
name = "precachedctl"
path = "src/bin/precachedctl/src/main.rs"

[[bin]]
name = "iotracectl"
path = "src/bin/iotracectl/src/main.rs"
