[package]
name = "precached"
version = "0.1.0"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]

[dependencies]
procmon-sys = { version = "0.0.2", path = 'src/procmon-sys' }
sys-info = { git = "https://github.com/X3n0m0rph59/sys-info-rs" }
chrono = { version = "0.4.0", features = ["serde"] }
libc = "0.2.32"
nix = "0.9"
log = "0.3"
env_logger = "0.4.3"
pretty_env_logger = "0.1.1"
fern = "0.4"
ansi_term = "0.10.2"
syslog = "~3.3.0"
lazy_static = "0.2.8"
netlink-rs = "0.0.3"
regex = "0.2"
fnv = "1.0.5"
globset = "0.2"
byteorder = "1.1.0"
bytevec = "0.2.0"
threadpool = "1.0"
toml = "0.4"
clap = "2.26.2"
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"
zstd = "0.4.14"
dbus = "0.5.4"
notify-rust = "3"

# [workspace]
# members = ["src/bin/precachedctl", "src/bin/iotrace"]

[[bin]]
name = "precachedctl"
path = "src/bin/precachedctl/src/main.rs"

[[bin]]
name = "precached-iotrace"
path = "src/bin/iotrace/src/main.rs"
