[package]
name = "precached"
version = "0.1.0"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
description = "A Linux process monitor and pre-caching daemon"
repository = "https://github.com/X3n0m0rph59/precached"
homepage = "https://x3n0m0rph59.github.io/precached/"
license = "GPLv3+"
readme = "README.md"

[features]
default = []
dev = ["clippy"]

[dependencies]
procmon-sys = { version = "0.0.2", path = 'src/procmon-sys' }
sys-info = { version = "*", git = "https://github.com/X3n0m0rph59/sys-info-rs", branch = "master" }
threadpool = { version = "*", git = "https://github.com/X3n0m0rph59/rust-threadpool", branch = "master" }
# sys-info = { version = "*", path = "vendor/sys-info" }
# threadpool = { version = "*", path = "vendor/threadpool" }
chrono = { version = "0.4.0", features = ["serde"] }
log-panics = "1.2.0"
ordermap = "0.3.0"
systemstat = "0.1.2"
libc = "0.2.33"
nix = "0.9"
num_cpus = "1.0"
log = "0.3"
env_logger = "0.4.3"
pretty_env_logger = "0.1.1"
fern = "0.4"
ansi_term = "0.10.2"
syslog = "~3.3.0"
lazy_static = "0.2.10"
regex = "0.2"
fnv = "1.0.6"
globset = "0.2"
byteorder = "1.1.0"
bytevec = "0.2.0"
toml = "0.4"
clap = "2.27.1"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
zstd = "0.4.16"
dbus = "0.5.4"
notify-rust = "3"
term = "0.4.6"
prettytable-rs = "^0.6"
daemonize = "0.2.3"
clippy = { version = "*", optional = true }

# [replace]
# sys-info = { version = "*", path = "vendor/" }
# threadpool = { version = "*", path = "vendor/" }

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8
panic = 'unwind'

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'

[[bin]]
name = "precached"
path = "src/main.rs"

[[bin]]
name = "precachedctl"
path = "src/bin/precachedctl/src/main.rs"

[[bin]]
name = "iotracectl"
path = "src/bin/iotracectl/src/main.rs"
