.\" Manpage for precachedctl.
.TH man 8 "02. March 2020" "1.7.2" "precachedctl man page"
.SH NAME
 precachedctl - Control the precached daemon and manage plugins
.SH SYNOPSIS
 precachedctl [FLAGS] [OPTIONS] [SUBCOMMAND]
.SH DESCRIPTION
 Control the precached daemon.
.SH FLAGS
 -a, --ascii    Produce ASCII output instead of using Unicode for line drawing
 -v             Sets the level of output verbosity
 -h, --help     Prints help information
 -V, --version  Prints version information
.SH OPTIONS
 -c, --config <file>  The precached config file to use [default: /etc/precached/precached.conf]
.SH SUBCOMMANDS
 status        Show the current status of the precached daemon
 reload        Reload external configuration of precached
 stop          Instruct precached to shutdown and quit
 housekeeping  Instruct precached to commence housekeeping tasks
 prime-caches  Instruct precached to commence priming all caches now
 plugins       Manage precached daemon plugins
 help          Display this short help text
.SH PLUGINS
 Plugins can be managed with the subcommand `precachedctl plugins <plugin-name>`.
 Please find the list of manageable plugins and their supported commands below:

.SH hot-applications
 top           Show the top most entries in the histogram of hot applications
 list          Show all entries in the histogram of hot applications
 optimize      Optimize the histogram of hot applications
 help          Prints this message or the help of the given subcommand(s)

 For managing I/O trace log files generated by precached, please see iotracectl(8).

.SH SEE ALSO
 iotracectl(8), rulesctl(8), precachedtop(8), precached(8), precached.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
