.\" Manpage for precached.
.TH man 8 "21 Nov 2017" "1.0" "precached man page"
.SH NAME
 precached - A Linux process monitor and pre-caching daemon
.SH SYNOPSIS
 precached [FLAGS] [OPTIONS]
.SH DESCRIPTION
 Precached is written in Rust and utilizes the Linux netlink connector interface
 to monitor the system for process events. It can act upon such events via
 multiple means. E.g. in the future it will be able to pre-fault pages into
 memory to speed up loading of programs and increase the perceived snappiness
 of the system.
.SH FLAGS
 -f, --foreground    Stay in foreground (do not daemonize)
 -h, --help          Prints help information
 -v                  Sets the level of log verbosity
 -V, --version       Prints version information
.SH OPTIONS
 -c, --config <FILE> Location of the configuration file
.SH SEE ALSO
 precachedctl(8), iotracectl(8), precached.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
