.\" Manpage for .rules file format.
.TH man 5 "31 Dec 2017" "1.0" ".rules file format man page"
.SH NAME
 rules - Overview of the precached rules file format
.SH SYNOPSIS
.SH DESCRIPTION
 The precached rules file mechanism allows for an easy customization of the behaviour of the precached daemon.
 This can be achieved using a simple declarative language.
.SH SEE ALSO
 iotracectl(8), precachedctl(8), rulesctl(8), precachedtop(8), precached(8), precached.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
