.\" Manpage for precachedctl.
.TH man 8 "09 Oct 2017" "1.0" "precachedctl man page"
.SH NAME
precachedctl - Control the precached
.SH SYNOPSIS
precachedctl [FLAGS] [OPTIONS]
.SH DESCRIPTION
.SH FLAGS
-h, --help    Prints help information
-v            Sets the level of verbosity
-V, --version Prints version information
.SH OPTIONS

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
X3n0m0rph59 (x3n0m0rph59@gmail.com)
