.\" Manpage for precached.
.TH man 5 "22 Dec 2017" "1.0" "precached.conf man page"
.SH NAME
 precached - A Linux process monitor and pre-caching daemon
.SH SYNOPSIS
.SH DESCRIPTION
.SH SEE ALSO
 iotracectl(8), precachedctl(8), precachedtop(8), rulesctl(8), precached(8)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
