.\" Manpage for precachedctl.
.TH man 8 "12 Oct 2017" "1.0" "precachedctl man page"
.SH NAME
 precachedctl - Control the precached daemon
.SH SYNOPSIS
 precachedctl [FLAGS] [OPTIONS] [SUBCOMMAND]
.SH DESCRIPTION
 Control the precached daemon.
.SH FLAGS
 -a, --ascii    Produce ASCII output instead of using Unicode for line drawing
 -v             Sets the level of output verbosity
 -h, --help     Prints help information
 -V, --version  Prints version information
.SH OPTIONS
 -c, --config <file>  The precached config file to use [default: /etc/precached/precached.conf]
.SH SUBCOMMANDS
 status        Show the current status of the precached daemon
 reload        Reload external configuration of precached
 stop          Instruct precached to shutdown and quit
 housekeeping  Instruct precached to commence housekeeping tasks
 help          Display this short help text
.SH SEE ALSO
 iotracectl(8), precached(8), precached.conf(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
