.\" Manpage for rulesctl.
.TH man 8 "16. February 2018" "1.7.0" "rulesctl man page"
.SH NAME
 rulesctl - Manage rules engine of the precached daemon
.SH SYNOPSIS
 rulesctl [FLAGS] [OPTIONS] [SUBCOMMAND]
.SH DESCRIPTION
 Manage rules engine of the precached daemon
.SH FLAGS
 -a, --ascii      Produce ASCII output (default) instead of using Unicode for line drawing
 -u, --unicode    Produce Unicode output instead of using ASCII (default) for line drawing
 -v               Sets the level of output verbosity
 -h, --help       Prints help information
 -V, --version    Prints version information
.SH OPTIONS
 -c, --config <file>  The precached config file to use [default: /etc/precached/precached.conf]
.SH SUBCOMMANDS 
 status    Show the current status of the precached rules subsystem
 list      List all available .rules files
 show      Print information about a specific .rules file
 reload    Tell precached to reload its configuration
 help      Display this short help text


 rulesctl is a tool for managing precached .rules files.

.SH SEE ALSO
 iotracectl(8), precachedctl(8), precachedtop(8), precached(8), precached.conf(5), precached.rules(5)
.SH BUGS
 No known bugs.
.SH AUTHOR
 X3n0m0rph59 <x3n0m0rph59@gmail.com>
