cargo-features = ["edition"]

[package]
edition = "2018"
name = "procmon-sys"
version = "0.0.2"
build = "build.rs"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
license = "GPLv3+"

[lib]

[dependencies]
libc = "0.2.43"

[build-dependencies]
gcc = "0.3"
