refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} [{h({l})}]: {M}:{L} - {m}{n}"
      
  syslog:
    kind: libc-syslog
    openlog:
      ident: precached
      option: LOG_PID | LOG_NDELAY | LOG_CONS
      facility: Daemon
    level_map:
      Error: LOG_CRIT
      Warn: LOG_WARNING
      Info: LOG_INFO
      Debug: LOG_DEBUG
      Trace: LOG_DEBUG
    encoder:
      pattern: "{M}:{L} - {m}"

  # logfile:
  #   kind: file
  #   path: "/var/log/precached.log"
  #   encoder:
  #     pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} [{l}]: {M}:{L} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - syslog
  # - logfile
